services:
  fastapi-server:
    build: .
    container_name: game-siteruzou-server
    ports:
      - "8000:8000"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    restart: unless-stopped
